
import { WorkoutTemplate } from './types';
import { v4 as uuidv4 } from 'uuid';

// Helper function to generate a UUID for each template
const generateId = () => uuidv4();

// Empty exercise template to use in each workout template
const emptyExercises = [
  {
    name: "",
    sets: "",
    reps: "",
    restPeriod: "",
    equipment: [],
    targetMuscles: [],
    notes: ""
  }
];

export const workoutTemplates: WorkoutTemplate[] = [
  {
    id: generateId(),
    title: "Upper Body Strength",
    type: "strength",
    category: "Upper Body",
    duration: "45 minutes",
    difficulty: "intermediate",
    calories: "300-400",
    intensity: "Medium-High",
    spaceRequired: "Small",
    equipment: ["Dumbbells", "Bench"],
    targetMuscles: ["Chest", "Shoulders", "Triceps", "Back", "Biceps"],
    frequency: "2-3 times per week",
    description: "A comprehensive upper body workout focusing on building strength and definition.",
    benefits: ["Increased upper body strength", "Improved posture", "Enhanced muscle definition"],
    alternatives: ["Push-up variations if no weights available"],
    target: "upper_body",
    exercises: emptyExercises
  },
  {
    id: generateId(),
    title: "HIIT Cardio",
    type: "cardio",
    category: "Full Body",
    duration: "30 minutes",
    difficulty: "intermediate",
    calories: "400-500",
    intensity: "High",
    spaceRequired: "Small",
    equipment: ["None"],
    targetMuscles: ["Full Body", "Core"],
    frequency: "2-3 times per week",
    description: "High-intensity interval training to boost cardio fitness and burn calories.",
    benefits: ["Improved cardiovascular health", "Enhanced fat burning", "Increased metabolic rate"],
    tips: ["Focus on form over speed", "Adjust intensity as needed"],
    target: "fat_loss",
    exercises: emptyExercises
  },
  {
    id: generateId(),
    title: "Tabata Workout",
    type: "cardio",
    category: "Full Body",
    duration: "20 minutes",
    difficulty: "intermediate",
    calories: "250-350",
    intensity: "Very High",
    spaceRequired: "Small",
    equipment: ["Timer"],
    targetMuscles: ["Full Body", "Core"],
    frequency: "2 times per week",
    description: "Ultra-efficient 20-second work, 10-second rest intervals repeated for 4 minutes per exercise.",
    benefits: ["Time efficiency", "Improved anaerobic and aerobic capacity", "Calorie burning"],
    tips: ["Give maximum effort during work intervals", "Rest completely during rest intervals"],
    target: "fat_loss",
    exercises: emptyExercises
  },
  {
    id: generateId(),
    title: "Walking Program",
    type: "cardio",
    category: "Lower Body",
    duration: "30-60 minutes",
    difficulty: "beginner",
    calories: "150-300",
    intensity: "Low",
    spaceRequired: "Outdoor/Treadmill",
    equipment: ["Comfortable Shoes"],
    targetMuscles: ["Legs", "Glutes", "Core"],
    frequency: "Daily or 5 times per week",
    description: "A simple walking program ideal for beginners or active recovery days.",
    benefits: ["Improved mood", "Low-impact cardiovascular exercise", "Increased daily activity"],
    tips: ["Focus on posture", "Gradually increase pace and duration"],
    target: "health",
    exercises: emptyExercises
  },
  {
    id: generateId(),
    title: "Jump Rope Workout",
    type: "cardio",
    category: "Full Body",
    duration: "20 minutes",
    difficulty: "intermediate",
    calories: "200-300",
    intensity: "Medium-High",
    spaceRequired: "Small",
    equipment: ["Jump Rope"],
    targetMuscles: ["Calves", "Shoulders", "Core"],
    frequency: "3 times per week",
    description: "Efficient jump rope intervals to improve coordination and cardiovascular fitness.",
    benefits: ["Improved coordination", "Increased calorie burn", "Portable workout option"],
    tips: ["Start slow and build up", "Mix double jumps with single jumps"],
    target: "fat_loss",
    exercises: emptyExercises
  },
  {
    id: generateId(),
    title: "Bodyweight Basics",
    type: "strength",
    category: "Full Body",
    duration: "30 minutes",
    difficulty: "beginner",
    calories: "200-300",
    intensity: "Low-Medium",
    spaceRequired: "Small",
    equipment: ["None"],
    targetMuscles: ["Chest", "Core", "Legs", "Arms"],
    frequency: "3 times per week",
    description: "A simple bodyweight routine perfect for beginners.",
    benefits: ["Build foundational strength", "Learn proper form", "No equipment needed"],
    tips: ["Focus on controlled movements", "Increase reps as you progress"],
    target: "strength",
    exercises: emptyExercises
  },
  {
    id: generateId(),
    title: "Dumbbell Full Body",
    type: "strength",
    category: "Full Body",
    duration: "45 minutes",
    difficulty: "intermediate",
    calories: "300-400",
    intensity: "Medium",
    spaceRequired: "Small",
    equipment: ["Dumbbells"],
    targetMuscles: ["Chest", "Back", "Shoulders", "Arms", "Legs"],
    frequency: "3 times per week",
    description: "Complete full body workout using only dumbbells.",
    benefits: ["Full body strength development", "Versatile workout", "Time-efficient"],
    tips: ["Choose appropriate weight for each exercise", "Focus on controlled form"],
    target: "strength",
    exercises: emptyExercises
  },
  {
    id: generateId(),
    title: "Beginner Yoga Flow",
    type: "flexibility",
    category: "Full Body",
    duration: "30 minutes",
    difficulty: "beginner",
    calories: "100-150",
    intensity: "Low",
    spaceRequired: "Small",
    equipment: ["Yoga Mat"],
    targetMuscles: ["Full Body", "Core"],
    frequency: "Daily or 3-4 times per week",
    description: "Gentle yoga sequence focusing on basic poses and breathing.",
    benefits: ["Improved flexibility", "Stress reduction", "Better body awareness"],
    tips: ["Focus on breathing", "Don't force poses", "Use modifications as needed"],
    target: "flexibility",
    exercises: emptyExercises
  },
  {
    id: generateId(),
    title: "Intermediate Yoga",
    type: "flexibility",
    category: "Full Body",
    duration: "45 minutes",
    difficulty: "intermediate",
    calories: "150-250",
    intensity: "Medium",
    spaceRequired: "Small",
    equipment: ["Yoga Mat"],
    targetMuscles: ["Full Body", "Core"],
    frequency: "3-4 times per week",
    description: "More challenging yoga routine with flowing sequences and longer holds.",
    benefits: ["Enhanced flexibility", "Improved balance", "Core strength development"],
    tips: ["Build on foundation poses", "Focus on alignment", "Listen to your body"],
    target: "flexibility",
    exercises: emptyExercises
  },
  {
    id: generateId(),
    title: "Morning Stretch Routine",
    type: "flexibility",
    category: "Full Body",
    duration: "15 minutes",
    difficulty: "beginner",
    calories: "50-100",
    intensity: "Low",
    spaceRequired: "Small",
    equipment: ["None"],
    targetMuscles: ["Full Body"],
    frequency: "Daily",
    description: "Quick morning stretching routine to wake up your body.",
    benefits: ["Increased morning energy", "Improved circulation", "Reduced stiffness"],
    tips: ["Do this routine right after waking up", "Hold each stretch for 20-30 seconds"],
    target: "flexibility",
    exercises: emptyExercises
  },
  {
    id: generateId(),
    title: "Office Stretch Break",
    type: "flexibility",
    category: "Full Body",
    duration: "10 minutes",
    difficulty: "beginner",
    calories: "30-50",
    intensity: "Low",
    spaceRequired: "Small",
    equipment: ["Chair"],
    targetMuscles: ["Neck", "Shoulders", "Back", "Hips"],
    frequency: "Daily, multiple times",
    description: "Quick stretches that can be done at your desk to relieve tension.",
    benefits: ["Reduced workplace stiffness", "Improved focus", "Decreased muscle tension"],
    tips: ["Set a reminder to stretch every hour", "Focus on areas of tension"],
    target: "mobility",
    exercises: emptyExercises
  },
  {
    id: generateId(),
    title: "Mobility Flow",
    type: "flexibility",
    category: "Full Body",
    duration: "20 minutes",
    difficulty: "intermediate",
    calories: "100-150",
    intensity: "Low-Medium",
    spaceRequired: "Small",
    equipment: ["Foam Roller"],
    targetMuscles: ["Joints", "Full Body"],
    frequency: "3-4 times per week",
    description: "Dynamic movements to improve joint mobility and movement patterns.",
    benefits: ["Improved movement quality", "Reduced joint pain", "Better workout performance"],
    tips: ["Move slowly through ranges of motion", "Focus on areas of restriction"],
    target: "mobility",
    exercises: emptyExercises
  },
  {
    id: generateId(),
    title: "Sprint Intervals",
    type: "cardio",
    category: "Lower Body",
    duration: "30 minutes",
    difficulty: "advanced",
    calories: "350-450",
    intensity: "Very High",
    spaceRequired: "Track/Field/Treadmill",
    equipment: ["None"],
    targetMuscles: ["Legs", "Glutes", "Core"],
    frequency: "1-2 times per week",
    description: "High-intensity sprint training to build speed and power.",
    benefits: ["Increased explosive power", "Improved anaerobic capacity", "Efficient calorie burning"],
    tips: ["Warm up thoroughly", "Start with shorter sprints", "Full recovery between sets"],
    target: "power",
    exercises: emptyExercises
  },
  {
    id: generateId(),
    title: "Hill Repeats",
    type: "cardio",
    category: "Lower Body",
    duration: "40 minutes",
    difficulty: "advanced",
    calories: "400-500",
    intensity: "High",
    spaceRequired: "Outdoor Hill",
    equipment: ["None"],
    targetMuscles: ["Quads", "Hamstrings", "Glutes", "Calves"],
    frequency: "1-2 times per week",
    description: "Running or walking uphill repeatedly to build lower body strength and endurance.",
    benefits: ["Increased leg strength", "Improved running economy", "Cardiovascular benefits"],
    tips: ["Focus on driving knees and arms", "Control downhill portions", "Start with fewer repeats"],
    target: "endurance",
    exercises: emptyExercises
  },
  {
    id: generateId(),
    title: "Kettlebell Circuit",
    type: "strength",
    category: "Full Body",
    duration: "30 minutes",
    difficulty: "intermediate",
    calories: "300-400",
    intensity: "Medium-High",
    spaceRequired: "Small",
    equipment: ["Kettlebell"],
    targetMuscles: ["Full Body", "Core", "Shoulders"],
    frequency: "2-3 times per week",
    description: "Dynamic kettlebell exercises combined into an efficient circuit.",
    benefits: ["Functional strength", "Cardiovascular conditioning", "Core stability"],
    tips: ["Focus on proper swing technique", "Start with lighter weight", "Maintain a braced core"],
    target: "strength",
    exercises: emptyExercises
  },
  {
    id: generateId(),
    title: "Power Lifting",
    type: "strength",
    category: "Full Body",
    duration: "60 minutes",
    difficulty: "advanced",
    calories: "400-500",
    intensity: "High",
    spaceRequired: "Gym",
    equipment: ["Barbell", "Squat Rack", "Bench", "Weight Plates"],
    targetMuscles: ["Legs", "Back", "Chest", "Shoulders"],
    frequency: "3-4 times per week",
    description: "Focus on the main compound lifts: squat, bench press, deadlift.",
    benefits: ["Maximum strength gains", "Increased muscle mass", "Improved bone density"],
    tips: ["Focus on proper form", "Increase weight gradually", "Allow adequate recovery"],
    target: "strength",
    exercises: emptyExercises
  },
  {
    id: generateId(),
    title: "Active Recovery",
    type: "flexibility",
    category: "Full Body",
    duration: "30 minutes",
    difficulty: "beginner",
    calories: "100-150",
    intensity: "Low",
    spaceRequired: "Small",
    equipment: ["Foam Roller", "Yoga Mat"],
    targetMuscles: ["Full Body"],
    frequency: "1-2 times per week",
    description: "Light activity and stretching to promote recovery between harder workouts.",
    benefits: ["Enhanced recovery", "Reduced muscle soreness", "Improved circulation"],
    tips: ["Keep intensity very light", "Focus on problem areas", "Use as a rest day alternative"],
    target: "recovery",
    exercises: emptyExercises
  }
];
