
import { Exercise, WorkoutTemplate } from "./types";
import { v4 as uuidv4 } from "uuid";

// Default exercise sets for templates
const strengthExercises: Exercise[] = [
  {
    name: "Push-ups",
    sets: "3",
    reps: "10",
    restPeriod: "60",
    equipment: ["Bodyweight"],
    targetMuscles: ["Chest", "Shoulders", "Triceps"],
    notes: "Keep body straight, lower until chest nearly touches ground"
  },
  {
    name: "Squats",
    sets: "3",
    reps: "12",
    restPeriod: "60",
    equipment: ["Bodyweight"],
    targetMuscles: ["Quadriceps", "Hamstrings", "Glutes"],
    notes: "Keep weight in heels, maintain neutral spine"
  },
  {
    name: "Dumbbell Rows",
    sets: "3",
    reps: "10",
    restPeriod: "60",
    equipment: ["Dumbbells"],
    targetMuscles: ["Back", "Biceps"],
    notes: "Keep back flat, pull dumbbell to hip"
  }
];

const cardioExercises: Exercise[] = [
  {
    name: "Jumping Jacks",
    sets: "3",
    reps: "30",
    restPeriod: "30",
    equipment: ["Bodyweight"],
    targetMuscles: ["Full Body"],
    notes: "Maintain rhythm, keep core engaged"
  },
  {
    name: "High Knees",
    sets: "3",
    reps: "40",
    restPeriod: "30",
    equipment: ["Bodyweight"],
    targetMuscles: ["Core", "Quadriceps"],
    notes: "Bring knees up to hip level, maintain quick pace"
  },
  {
    name: "Mountain Climbers",
    sets: "3",
    reps: "30",
    restPeriod: "30",
    equipment: ["Bodyweight"],
    targetMuscles: ["Core", "Shoulders"],
    notes: "Keep hips down, alternate knees to chest quickly"
  }
];

const flexibilityExercises: Exercise[] = [
  {
    name: "Hamstring Stretch",
    sets: "3",
    reps: "1",
    restPeriod: "0",
    equipment: ["Bodyweight", "Yoga Mat"],
    targetMuscles: ["Hamstrings"],
    notes: "Hold for 30 seconds, no bouncing"
  },
  {
    name: "Cobra Pose",
    sets: "3",
    reps: "1",
    restPeriod: "0",
    equipment: ["Yoga Mat"],
    targetMuscles: ["Back", "Abs"],
    notes: "Lift chest while keeping hips on ground, hold for 20 seconds"
  },
  {
    name: "Butterfly Stretch",
    sets: "3",
    reps: "1",
    restPeriod: "0",
    equipment: ["Yoga Mat"],
    targetMuscles: ["Hip Flexors", "Glutes"],
    notes: "Press knees down gently, hold for 30 seconds"
  }
];

// Helper function to create template IDs
const createTemplateId = () => uuidv4();

export const workoutTemplates: WorkoutTemplate[] = [
  {
    id: createTemplateId(),
    title: "Beginner Strength Training",
    type: "strength",
    category: "Beginner Friendly",
    target: "Full Body",
    duration: "30",
    difficulty: "beginner",
    calories: "250",
    intensity: "Low",
    spaceRequired: "Small",
    equipment: ["Dumbbells", "Bodyweight"],
    targetMuscles: ["Chest", "Back", "Legs", "Core"],
    frequency: "2-3 times per week",
    description: "A simple strength routine perfect for beginners focusing on the main muscle groups.",
    benefits: ["Builds basic strength", "Improves posture", "Increases metabolism"],
    tips: ["Focus on form over weight", "Rest 1-2 days between sessions", "Increase weight gradually"],
    exercises: strengthExercises,
    notes: "Great starter workout for building strength foundations."
  },
  {
    id: createTemplateId(),
    title: "HIIT Cardio Blast",
    type: "cardio",
    category: "Fat Burning",
    target: "Cardiovascular",
    duration: "20",
    difficulty: "intermediate",
    calories: "300",
    intensity: "High",
    spaceRequired: "Small",
    equipment: ["Bodyweight"],
    targetMuscles: ["Heart", "Lungs", "Full Body"],
    frequency: "2-3 times per week",
    description: "High-intensity interval training to maximize calorie burn in minimal time.",
    benefits: ["Burns fat efficiently", "Improves cardiovascular health", "Boosts metabolism after workout"],
    tips: ["Push hard during work intervals", "Take full rest periods", "Modify exercises as needed"],
    exercises: cardioExercises,
    notes: "This workout is great for burning calories in a short amount of time."
  },
  {
    id: createTemplateId(),
    title: "Tabata Training",
    type: "cardio",
    category: "Fat Burning",
    target: "Cardiovascular",
    duration: "20",
    difficulty: "intermediate",
    calories: "250",
    intensity: "Very High",
    spaceRequired: "Small",
    equipment: ["Bodyweight", "Timer"],
    targetMuscles: ["Full Body"],
    frequency: "2 times per week",
    description: "20 seconds of all-out effort followed by 10 seconds of rest, repeated 8 times per exercise.",
    benefits: ["Extremely time-efficient", "Improves both aerobic and anaerobic fitness", "Continues burning calories after workout"],
    tips: ["Go all-out during work periods", "Keep strict timing", "Quality over quantity of reps"],
    exercises: cardioExercises,
    notes: "One of the most efficient workouts for improving conditioning."
  },
  {
    id: createTemplateId(),
    title: "Morning Energizer",
    type: "cardio",
    category: "Energy Boosting",
    target: "Full Body",
    duration: "15",
    difficulty: "beginner",
    calories: "150",
    intensity: "Moderate",
    spaceRequired: "Small",
    equipment: ["Bodyweight"],
    targetMuscles: ["Full Body"],
    frequency: "Daily",
    description: "A quick morning routine to get your blood flowing and energy levels up for the day.",
    benefits: ["Kickstarts metabolism", "Improves mood", "Increases alertness"],
    tips: ["Do it right after waking up", "No equipment needed", "Can be done in pajamas!"],
    exercises: cardioExercises,
    notes: "Perfect for starting your day with a boost of energy."
  },
  {
    id: createTemplateId(),
    title: "Lunch Break Express",
    type: "cardio",
    category: "Quick Workouts",
    target: "Cardiovascular",
    duration: "15",
    difficulty: "intermediate",
    calories: "200",
    intensity: "Moderate to High",
    spaceRequired: "Small",
    equipment: ["Bodyweight"],
    targetMuscles: ["Full Body"],
    frequency: "3-5 times per week",
    description: "Fast-paced workout that fits perfectly into a busy lunch break.",
    benefits: ["Beats afternoon slump", "Fits into busy schedule", "No shower required if modified"],
    tips: ["Have a light lunch after", "Keep a change of clothes at work", "Focus on no-sweat options if needed"],
    exercises: cardioExercises,
    notes: "Great for busy professionals who need a midday energy boost."
  },
  {
    id: createTemplateId(),
    title: "Bodyweight Basics",
    type: "strength",
    category: "No Equipment",
    target: "Full Body",
    duration: "25",
    difficulty: "beginner",
    calories: "200",
    intensity: "Low to Moderate",
    spaceRequired: "Small",
    equipment: ["Bodyweight"],
    targetMuscles: ["Chest", "Back", "Legs", "Core"],
    frequency: "3 times per week",
    description: "Build strength using just your bodyweight with these fundamental exercises.",
    benefits: ["No equipment needed", "Can be done anywhere", "Builds functional strength"],
    tips: ["Focus on form", "Increase reps as you get stronger", "Add variations to increase difficulty"],
    exercises: strengthExercises,
    notes: "The perfect routine for when you have no access to gym equipment."
  },
  {
    id: createTemplateId(),
    title: "Dumbbell Full Body",
    type: "strength",
    category: "Strength Building",
    target: "Full Body",
    duration: "40",
    difficulty: "intermediate",
    calories: "350",
    intensity: "Moderate",
    spaceRequired: "Small",
    equipment: ["Dumbbells", "Bench"],
    targetMuscles: ["Chest", "Back", "Shoulders", "Arms", "Legs"],
    frequency: "3 times per week",
    description: "Complete strength workout using just a pair of dumbbells to target all major muscle groups.",
    benefits: ["Minimal equipment required", "Balanced muscle development", "Improved functional strength"],
    tips: ["Choose appropriate weight", "Rest 60-90 seconds between sets", "Increase weight gradually"],
    exercises: strengthExercises,
    notes: "Effective full-body strength training with minimal equipment."
  },
  {
    id: createTemplateId(),
    title: "Basic Stretching Routine",
    type: "flexibility",
    category: "Recovery",
    target: "Full Body",
    duration: "15",
    difficulty: "beginner",
    calories: "50",
    intensity: "Low",
    spaceRequired: "Small",
    equipment: ["Yoga Mat"],
    targetMuscles: ["Full Body"],
    frequency: "Daily",
    description: "Simple stretching routine to improve flexibility and reduce muscle tension.",
    benefits: ["Reduces muscle soreness", "Improves range of motion", "Helps prevent injuries"],
    tips: ["Hold each stretch 20-30 seconds", "Breathe deeply", "No bouncing"],
    exercises: flexibilityExercises,
    notes: "Great for post-workout recovery or as a standalone session."
  },
  {
    id: createTemplateId(),
    title: "Yoga Flow",
    type: "flexibility",
    category: "Mind-Body",
    target: "Full Body",
    duration: "30",
    difficulty: "intermediate",
    calories: "150",
    intensity: "Low to Moderate",
    spaceRequired: "Medium",
    equipment: ["Yoga Mat"],
    targetMuscles: ["Core", "Back", "Legs", "Arms"],
    frequency: "2-4 times per week",
    description: "Flowing yoga sequence combining strength, flexibility, and mindfulness.",
    benefits: ["Improves flexibility", "Reduces stress", "Enhances balance"],
    tips: ["Focus on breath", "Move slowly between poses", "Modify poses as needed"],
    exercises: flexibilityExercises,
    notes: "Great for improving both mental and physical wellbeing."
  },
  {
    id: createTemplateId(),
    title: "Morning Stretch",
    type: "flexibility",
    category: "Energy Boosting",
    target: "Full Body",
    duration: "10",
    difficulty: "beginner",
    calories: "40",
    intensity: "Low",
    spaceRequired: "Small",
    equipment: ["Yoga Mat"],
    targetMuscles: ["Back", "Shoulders", "Hamstrings"],
    frequency: "Daily",
    description: "Quick morning stretching routine to wake up your body and prepare for the day.",
    benefits: ["Increases blood flow", "Reduces morning stiffness", "Improves alertness"],
    tips: ["Do right after waking up", "Focus on gentle movements", "Breathe deeply"],
    exercises: flexibilityExercises,
    notes: "A gentle way to start your day and prepare your body for activity."
  },
  {
    id: createTemplateId(),
    title: "Office Break Stretches",
    type: "flexibility",
    category: "Workplace",
    target: "Upper Body",
    duration: "5",
    difficulty: "beginner",
    calories: "20",
    intensity: "Very Low",
    spaceRequired: "Very Small",
    equipment: ["Chair"],
    targetMuscles: ["Neck", "Shoulders", "Wrists", "Back"],
    frequency: "Multiple times daily",
    description: "Quick desk-friendly stretches to relieve tension from sitting.",
    benefits: ["Reduces workplace strain", "Improves posture", "Prevents stiffness"],
    tips: ["Can be done right at your desk", "Set reminders to stretch hourly", "Focus on problem areas"],
    exercises: flexibilityExercises,
    notes: "Perfect for office workers to prevent pain from prolonged sitting."
  },
  {
    id: createTemplateId(),
    title: "Evening Relaxation",
    type: "flexibility",
    category: "Recovery",
    target: "Full Body",
    duration: "20",
    difficulty: "intermediate",
    calories: "80",
    intensity: "Low",
    spaceRequired: "Medium",
    equipment: ["Yoga Mat", "Pillow"],
    targetMuscles: ["Full Body"],
    frequency: "Daily",
    description: "Gentle stretching routine to release tension and prepare your body for sleep.",
    benefits: ["Improves sleep quality", "Reduces stress", "Releases daily tension"],
    tips: ["Dim lights while performing", "Focus on deep breathing", "Hold stretches longer"],
    exercises: flexibilityExercises,
    notes: "Helps transition your body from activity to rest for better sleep."
  },
  {
    id: createTemplateId(),
    title: "Sprint Intervals",
    type: "cardio",
    category: "Performance",
    target: "Lower Body",
    duration: "25",
    difficulty: "advanced",
    calories: "400",
    intensity: "Very High",
    spaceRequired: "Large",
    equipment: ["Timer", "Track or Open Space"],
    targetMuscles: ["Legs", "Glutes", "Core"],
    frequency: "1-2 times per week",
    description: "High-intensity sprint training to build speed, power and cardiovascular fitness.",
    benefits: ["Increases explosive power", "Burns fat efficiently", "Improves running economy"],
    tips: ["Warm up thoroughly", "Start with fewer intervals", "Full recovery between sprints"],
    exercises: cardioExercises,
    notes: "Extremely effective for improving cardiovascular fitness and burning fat."
  },
  {
    id: createTemplateId(),
    title: "Stair Workout",
    type: "cardio",
    category: "Fat Burning",
    target: "Lower Body",
    duration: "30",
    difficulty: "advanced",
    calories: "350",
    intensity: "High",
    spaceRequired: "Staircase",
    equipment: ["Stairs", "Timer"],
    targetMuscles: ["Quads", "Glutes", "Calves", "Core"],
    frequency: "2 times per week",
    description: "Challenging stair-based cardio routine that builds leg strength and cardiovascular endurance.",
    benefits: ["Builds leg strength", "Improves cardiovascular fitness", "Burns calories efficiently"],
    tips: ["Watch your footing", "Use handrails for safety", "Start with shorter intervals"],
    exercises: cardioExercises,
    notes: "A challenging workout that requires minimal equipment but delivers maximum results."
  },
  {
    id: createTemplateId(),
    title: "Kettlebell Circuit",
    type: "strength",
    category: "Strength Building",
    target: "Full Body",
    duration: "35",
    difficulty: "intermediate",
    calories: "300",
    intensity: "Moderate to High",
    spaceRequired: "Medium",
    equipment: ["Kettlebell"],
    targetMuscles: ["Full Body"],
    frequency: "3 times per week",
    description: "Dynamic kettlebell exercises combined in a circuit to build strength and conditioning.",
    benefits: ["Combines strength and cardio", "Improves core stability", "Builds functional strength"],
    tips: ["Master technique before increasing weight", "Focus on hip hinge movements", "Keep core engaged"],
    exercises: strengthExercises,
    notes: "Effective for building overall strength, power, and endurance."
  },
  {
    id: createTemplateId(),
    title: "Power Lifting Basics",
    type: "strength",
    category: "Strength Building",
    target: "Full Body",
    duration: "60",
    difficulty: "advanced",
    calories: "450",
    intensity: "High",
    spaceRequired: "Gym",
    equipment: ["Barbell", "Bench", "Squat Rack"],
    targetMuscles: ["Chest", "Back", "Legs"],
    frequency: "3-4 times per week",
    description: "Foundational powerlifting routine focusing on the big three: squat, bench press, and deadlift.",
    benefits: ["Maximizes strength gains", "Builds dense muscle", "Improves bone density"],
    tips: ["Focus on perfect form", "Progressive overload", "Allow adequate recovery"],
    exercises: strengthExercises,
    notes: "Classic strength training approach for serious strength development."
  },
  {
    id: createTemplateId(),
    title: "Pilates Fundamentals",
    type: "flexibility",
    category: "Core Strength",
    target: "Core",
    duration: "40",
    difficulty: "beginner",
    calories: "200",
    intensity: "Low to Moderate",
    spaceRequired: "Medium",
    equipment: ["Yoga Mat"],
    targetMuscles: ["Core", "Back", "Glutes"],
    frequency: "2-3 times per week",
    description: "Introduction to core Pilates movements focusing on control, precision, and core stability.",
    benefits: ["Improves core strength", "Enhances posture", "Develops body awareness"],
    tips: ["Focus on controlled movements", "Engage core continuously", "Quality over quantity"],
    exercises: flexibilityExercises,
    notes: "Excellent for developing core strength and improving posture."
  }
];
