// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmgqiarvycoowwhjhsfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtZ3FpYXJ2eWNvb3d3aGpoc2ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwNjk5MTYsImV4cCI6MjA1MjY0NTkxNn0.6BN_GdO9JiGqmMed7WarNU99_FvyCvx-_EnzhNBDo1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);